# HTTP Server
server:
  port: 12032  # HTTP (Tomcat) port

spring:
  data:
    mongodb:
      host: ts-order-other-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
#      database: piggymetrics
      port: 27017