spring:
  application:
    name: ts-sso-service
  data:
    mongodb:
      host: ts-account-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: rabbitmq
    listener:
      retry:
        enabled: false
        max-attempts: 1
    template:
      retry:
        enabled: false
        max-attempts: 1
  cloud:
    stream:
      bindings:
        output:
          group: ts-sso
          destination: ts-return-login-to-sso
          contentType: text/plain
          binder: rabbit
        input:
          group: ts-login
          destination: ts-login-to-sso
          contentType: text/plain
          binder: rabbit



# HTTP Server
server:
  port: 12349  # HTTP (Tomcat) port